# Use a lightweight Python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy application files to the container
COPY . /app

# Install dependencies if you have a requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt

# Expose the application port
EXPOSE 80

# Command to run the application
CMD ["python", "app.py"]